language: node_js

node_js: stable

cache: npm

install:
  - npm install

before_deploy:
  - hexo c
  - hexo g

deploy:
  provider: pages
  target_branch: master
  github-token: $GITHUB_TOKEN
  local_dir: public
  skip_cleanup: true
  fqdn: cosamuel.tech
  on:
    branch: develop
