language: node_js

node_js: stable

cache: npm

install:
  - npm install

script:
  - hexo g


deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: public
  skip_cleanup: true
  fqdn: cosamuel.tech
  on:
    branch: master
