language: node_js

node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm i -g hexo

script:
  - hexo clean
  - hexo g

after_script:
  
  - cd ./public
  - touch CNAME
  - echo "cosamuel.tech" >> CNAME

  - git init
  - git add .
  - git commit -m "Site Update:`date +' %Y-%m-%d %H:%m:%S'`"
  - git push --force --quiet "https://$GITHUB_TOKEN@github.com/CooSamuel/CooSamuel.github.io.git" master:master

deploy:
  provider: npm
  github-token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
