language: node_js

node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm i -g hexo

script:
  - hexo clean
  - hexo g

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: public
  skip_cleanup: true
  on:
    branch: gh-pages
